### ISSUE TITLE
syetm I/O error 

### ISSUE THREAD

**Issue by BDehury85** [rjdkmr/gmx_clusterByFeatures#2]
:-)  gmx_clusterByFeatures cluster (-:

             Author: Rajendra Kumar

       Copyright (C) 2018-2019  Rajendra Kumar

gmx_clusterByFeatures is a free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

gmx_clusterByFeatures is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with gmx_clusterByFeatures.  If not, see <http://www.gnu.org/licenses/>.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
    
=======================
  Cluster Log output   
=======================

Command:
=======================
cluster -s md_0_1.tpr -f md1.xtc -feat proj.xvg -method kmeans -nfeature 20 -cmetric ssr-sst -ncluster 15 -fit2central -sort features -cpdb central.pdb -fout cluster.xtc -plot pca_cluster.png
=======================
Reading file md_0_1.tpr, VERSION 2018.2 (single precision)
Reading file md_0_1.tpr, VERSION 2018.2 (single precision)

Choose a group for the output:

-------------------------------------------------------
Program:     cluster, version 2016.5
Source file: src/gromacs/utility/datafilefinder.cpp (line 210)
Function:    std::string gmx::DataFileFinder::findFile(const gmx::DataFileOptions&) const

System I/O error:
Library file 'residuetypes.dat' not found in current dir nor in your GMXLIB
path nor in the default directories.
The following paths were searched:
  /home/bd422/Desktop/BD/3 (current dir)
  /home/bd422/Desktop/BD/3/top
  /external/gromacs-2016.5/installed/share/gromacs/top (default)

**Comment by rjdkmr** [comment]
I have fixed the issue. Please update the package as instructed on the website.

**Comment by BDehury85** [comment]
Thanks a lot for the update. I will have a quick look into and get back to you soon.
