### ISSUE TITLE
pdb output issue

### ISSUE THREAD

**Issue by reinamauricette** [rjdkmr/gmx_clusterByFeatures#3]
Hi, I have been using gmx_clusterByFeatures to  cluster my trajectory. I want .pdb output and I have specified it on my command line,  however I am getting .xtc cluster output. I need to analyse the clusters generated and without a topology it is hard to use .xtc files. How can I get .pdb???

**Comment by rjdkmr** [comment]
Hi, Please use -cpdb option (https://gmx-clusterbyfeatures.readthedocs.io/en/latest/commands/cluster.html#cpdb-central-pdb). You can use these pdb file to load xtc files.
